name: Bump upstream Version

on:
  workflow_dispatch:
  schedule:
    - cron: "00 */4 * * *"
  push:
    branches:
      - "master"
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx @dappnode/dappnodesdk github-action bump-upstream --use-variants
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}
