name: "Main"
on:
  push:
    branches:
      - "main"
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "README.md"
  repository_dispatch:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ipfs-dev-gateway
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Publish
        run: npx @dappnode/dappnodesdk publish patch --github-release --content_provider=http://10.200.200.7:5001 --eth_provider=https://web3.dappnode.net --timeout 2h --all-variants
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEVELOPER_ADDRESS: "0xf35960302a07022aba880dffaec2fdd64d5bf1c1"
